APT::FTPArchive::Release::Origin "Repo Test";
APT::FTPArchive::Release::Label "Repo Test";
APT::FTPArchive::Release::Suite jammy;
APT::FTPArchive::Release::Codename jammy;
APT::FTPArchive::Release::Architectures amd64 ;
APT::FTPArchive::Release::Components main;
APT::FTPArchive::Release::Description "Repo Test (jammy)";
